version: '3'

services:

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "4242:5432"
    environment:
      POSTGRES_DATABASE: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "4242"
    volumes:
      - ${PWD}/db:/var/lib/postgresql/data
    networks:
      - ping-pong
    tty: true

  nginx:
    depends_on:
      - frontend
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ${PWD}/proxy/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - ping-pong
    tty: true

  backend:
    depends_on:
      - postgres
    build: ./backend
    image: backend
    container_name: backend
    restart: always
    expose:
        - "8000"
    networks:
      - ping-pong
    working_dir: /backend
    volumes:
      - ./backend:/backend
      - ./tools/backend.sh:/backend.sh
  
  frontend:
    depends_on:
      - backend
    build: ./frontend
    image: frontend
    container_name: frontend
    restart: always
    expose:
        - "3000"
    networks:
      - ping-pong
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
      - ./tools/frontend.sh:/frontend.sh
    environment:
      WDS_SOCKET_PORT: 0

networks:
  ping-pong:
    driver: bridge